/* Generated By:JavaCC: Do not edit this line. ProyectoCalculadoraConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProyectoCalculadoraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMA = 5;
  /** RegularExpression Id. */
  int RESTA = 6;
  /** RegularExpression Id. */
  int MULTIPLICACION = 7;
  /** RegularExpression Id. */
  int DIVISION = 8;
  /** RegularExpression Id. */
  int PARIZQ = 9;
  /** RegularExpression Id. */
  int PARDER = 10;
  /** RegularExpression Id. */
  int IGUAL = 11;
  /** RegularExpression Id. */
  int COMA = 12;
  /** RegularExpression Id. */
  int PCOMA = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int ENTERO = 15;
  /** RegularExpression Id. */
  int DOBLE = 16;
  /** RegularExpression Id. */
  int NUMINT = 17;
  /** RegularExpression Id. */
  int NUMDOUBLE = 18;
  /** RegularExpression Id. */
  int ETIQ = 19;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 20;
  /** RegularExpression Id. */
  int NUM = 21;
  /** RegularExpression Id. */
  int CORIZQ = 22;
  /** RegularExpression Id. */
  int CORDER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\"Evaluar\"",
    "<ENTERO>",
    "\"double\"",
    "<NUMINT>",
    "<NUMDOUBLE>",
    "<ETIQ>",
    "<IDENTIFICADOR>",
    "<NUM>",
    "\"[\"",
    "\"]\"",
  };

}
